apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  port: 9501
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/rekrutteringsbistand-api/
    - https://rekrutteringsbistand-api.dev.intern.nav.no/rekrutteringsbistand-api/
    - https://rekrutteringsbistand-api.dev-fss-pub.nais.io/rekrutteringsbistand-api/
  liveness:
    path: /rekrutteringsbistand-api/internal/actuator/health
    initialDelay: 30
  readiness:
    path: /rekrutteringsbistand-api/internal/actuator/health
    initialDelay: 30
  prometheus:
    enabled: true
    path: /rekrutteringsbistand-api/internal/actuator/prometheus
  vault:
    enabled: true
  webproxy: false
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: vis-stilling
          cluster: dev-gcp
        - application: rekrutteringsbistand-stilling-indekser
          cluster: dev-gcp
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: VIS_STILLING_CLIENT_ID
      value: 4d3876c0-dfae-4bad-aecf-4415d549954a
    - name: REKRUTTERINGSBISTAND_STILLING_INDEKSER_CLIENT_ID
      value: 685a0f3d-2a60-42a3-944d-252bb2b1093f
