apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: rekrutteringsbistand-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  port: 9501
  ingresses:
    - https://arbeidsgiver.nais.adeo.no/rekrutteringsbistand-api/
    - https://rekrutteringsbistand-api.intern.nav.no/rekrutteringsbistand-api/
    - https://rekrutteringsbistand-api.prod-fss-pub.nais.io/rekrutteringsbistand-api/
  liveness:
    path: /rekrutteringsbistand-api/internal/actuator/health
    initialDelay: 30
  readiness:
    path: /rekrutteringsbistand-api/internal/actuator/health
    initialDelay: 30
  prometheus:
    enabled: true
    path: /rekrutteringsbistand-api/internal/actuator/prometheus
  vault:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: vis-stilling
          cluster: prod-gcp
        - application: rekrutteringsbistand-stilling-indekser
          cluster: prod-gcp
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: VIS_STILLING_CLIENT_ID
      value: 5ab7c506-0441-4cc0-96ad-55d26b346975
    - name: REKRUTTERINGSBISTAND_STILLING_INDEKSER_CLIENT_ID
      value: a39eed0d-2f95-4384-b88e-55f9ebdf49ab

