apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: rekrutteringsbistand-stilling-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  port: 9501
  ingresses:
    - https://rekrutteringsbistand-stilling-api.intern.nav.no
    - https://rekrutteringsbistand-stilling-api.prod-fss-pub.nais.io
  liveness:
    path: /internal/actuator/health
    initialDelay: 30
  readiness:
    path: /internal/actuator/health
    initialDelay: 30
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  vault:
    enabled: true
  azure:
    application:
      enabled: true
