apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-stilling-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{version}}
  port: 9501
  ingresses:
    - {{ ingress }}
  liveness:
    path: /internal/actuator/health
    initialDelay: 30
  readiness:
    path: /internal/actuator/health
    initialDelay: 30
  replicas:
    max: {{ max_replicas }}
    min: {{ min_replicas }}
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: {{ postgres_tier }}
        diskAutoresize:  {{ disk_autoresize }}
        databases:
          - name: rekrutteringsbistand-stilling
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - NAVident
          - azp_name
        groups:
          - id: {{ ad_gruppe_modia_generell_tilgang }}    # adGruppeModiaGenerellTilgang
          - id: {{ ad_gruppe_jobbsokerrettet }}           # adGruppeJobbsøkerrettet
          - id: {{ ad_gruppe_arbeidsgiverrettet }}        # adGruppeArbeidsgiverrettet
          - id: {{ ad_gruppe_utvikler }}                  # adGruppeUtvikler
  kafka:
    pool: {{ kafka_pool }}
  secureLogs:
    enabled: true
  leaderElection: true
  accessPolicy:
    inbound:
      rules:
        - application: vis-stilling
        - application: rekrutteringsbistand-stilling-indekser
        - application: rekrutteringsbistand
        - application: rekrutteringsbistand-frontend
        - application: rekrutteringsbistand-kandidat-api
          cluster: {{ fss_cluster }}
        - application: rekrutteringsbistand-kandidatvarsel-api
        - application: toi-stilling-indekser
    outbound:
      external:
        - host: {{ ad_api_host }}
        - host: {{ rekrutteringsbistand_kandidat_api_host }}
        - host: {{ arbeidsmarked_openai_host }}
  envFrom:
    - secret: openai-toi-rekrutteringsbistand-stilling
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{ spring_profile }}
    - name: VIS_STILLING_AZP_NAME
      value: {{ vis_stilling_azp_name }}
    - name: KANDIDATVARSEL_AZP_NAME
      value: {{ kandidatvarsel_azp_name }}
    - name: REKRUTTERINGSBISTAND_STILLING_INDEKSER_AZP_NAME
      value: {{ rekrutteringsbistand_stilling_indekser_azp_name }}
    - name: TOI_STILLING_INDEKSER_AZP_NAME
      value: {{ toi_stilling_indekser_azp_name }}
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{ rekrutteringsbistand_stilling_group_id }}
    - name: KAFKA_RESET_POLICY
      value: "earliest"
    - name: AD_GRUPPE_JOBBSOKERRETTET
      value: {{ ad_gruppe_jobbsokerrettet }}
    - name: AD_GRUPPE_ARBEIDSGIVERRETTET
      value: {{ ad_gruppe_arbeidsgiverrettet }}
    - name: AD_GRUPPE_UTVIKLER
      value: {{ ad_gruppe_utvikler }}
