version: 2.1

commands:
  docker-build-and-push:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: docker build
          command: docker build -t "navikt/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1" .
      - run:
          name: docker push
          command: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin && docker push "navikt/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1"

jobs:
  build:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      # Download and cache Maven dependencies
      - restore_cache:
          keys:
            # fallback to using the latest cache if no exact match is found
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Build with Maven
          command: mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Verify that Docker image can be built
          command: docker build -t "navikt/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1" .
      - persist_to_workspace:
          root: .
          paths:
            - dev-nais.yaml
            - dev-alerts.yaml
            - prod-nais.yaml
            - prod-alerts.yaml
            - Dockerfile
            - /target/rekrutteringsbistand-api-0.0.1-SNAPSHOT.jar

  deploy-to-dev:
    docker:
      - image: navikt/deployment-cli:v0.4.2
    steps:
      - attach_workspace:
          at: .
      - docker-build-and-push
      - run: echo $GITHUB_PRIVATE_KEY | base64 -d | dos2unix > .circleci/github.key.pem # Handle MS Windows linebreak
      - run:
          name: dev-fss deployment
          command: deployment-cli deploy create --cluster dev-fss --resource dev-nais.yaml \
            --version navikt/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 --repository navikt/$CIRCLE_PROJECT_REPONAME --team teamtag --ref $CIRCLE_SHA1 --appid 43789 --key .circleci/github.key.pem
      - run: rm .circleci/github.key.pem

  deploy-to-prod:
    docker:
      - image: navikt/deployment-cli:v0.4.2
    steps:
      - attach_workspace:
          at: .
      - docker-build-and-push
      - run: echo $GITHUB_PRIVATE_KEY | base64 -d | dos2unix > .circleci/github.key.pem # Handle MS Windows linebreak
      - run:
          name: prod-fss deployment
          command: deployment-cli deploy create --cluster prod-fss --resource prod-nais.yaml \
            --version navikt/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 --repository navikt/$CIRCLE_PROJECT_REPONAME --team teamtag --ref $CIRCLE_SHA1 --appid 43789 --key .circleci/github.key.pem
      - run: rm .circleci/github.key.pem

workflows:
  version: 2
  my-workflow:
    jobs:
      - build
      - deploy-to-dev:
          name: "Deploy to cluster dev-fss"
          context: tag-ci # Needed for Docker Hub credentials and GITHUB_PRIVATE_KEY. Would rather like to use context "NAIS deploy"
          requires:
            - build
          filters:
            branches:
              only:
                - master
                ##### DEVELOPERS: Name your feature branch here if you want to deploy it to cluster dev-fss #####
                - circleci-massasje
                ##### ##### ##### ##### #####
      - approve-for-prod:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy-to-prod:
          name: "Deploy to cluster prod-fss"
          context: tag-ci # Needed for Docker Hub credentials and GITHUB_PRIVATE_KEY. Would rather like to use context "NAIS deploy"
          requires:
            - approve-for-prod
          filters:
            branches:
              only:
                - master