apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-stilling-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{version}}
  port: 9501
  ingresses:
    - https://rekrutteringsbistand-stilling-api.dev.intern.nav.no
  liveness:
    path: /internal/actuator/health
    initialDelay: 30
  readiness:
    path: /internal/actuator/health
    initialDelay: 30
  replicas:
    max: 1
    min: 1
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: rekrutteringsbistand-stilling
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
          - azp_name
  kafka:
    pool: nav-dev
  accessPolicy:
    inbound:
      rules:
        - application: vis-stilling
          namespace: arbeidsgiver
          cluster: dev-gcp
        - application: rekrutteringsbistand-stilling-indekser
          cluster: dev-gcp
          namespace: toi
        - application: rekrutteringsbistand-container
          namespace: toi
          cluster: dev-gcp
        - application: rekrutteringsbistand-kandidat-api
          namespace: toi
          cluster: dev-fss
    outbound:
      rules:
        - application: pam-ad-api
          cluster: dev-gcp
          namespace: teampam
        - application: rekrutteringsbistand-kandidat-api
          cluster: dev-fss
          namespace: toi
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: VIS_STILLING_URI
      value: "dev-gcp:arbeidsgiver:vis-stilling"
    - name: REKRUTTERINGSBISTAND_STILLING_INDEKSER_URI
      value: "dev-gcp:toi:rekrutteringsbistand-stilling-indekser"
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: rekrutteringsbistand-stilling-rapidconsumer-1
    - name: KAFKA_RESET_POLICY
      value: "earliest"