apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-stilling-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{version}}
  port: 9501
  ingresses:
    - https://rekrutteringsbistand-stilling-api.intern.dev.nav.no
  liveness:
    path: /internal/actuator/health
    initialDelay: 30
  readiness:
    path: /internal/actuator/health
    initialDelay: 30
  replicas:
    max: 1
    min: 1
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: db-f1-micro
        databases:
          - name: rekrutteringsbistand-stilling
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - NAVident
          - azp_name
        groups:
          - id: "67a06857-0028-4a90-bf4c-9c9a92c7d733"   # adGruppeModiaGenerellTilgang
          - id: "0dba8374-bf36-4d89-bbba-662447d57b94"   # adGruppeJobbsøkerrettet
          - id: "52bc2af7-38d1-468b-b68d-0f3a4de45af2"   # adGruppeArbeidsgiverrettet
          - id: "a1749d9a-52e0-4116-bb9f-935c38f6c74a"   # adGruppeUtvikler
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: vis-stilling
          namespace: arbeidsgiver
          cluster: dev-gcp
        - application: vis-stilling
          namespace: toi
          cluster: dev-gcp
        - application: rekrutteringsbistand-stilling-indekser
          cluster: dev-gcp
        - application: rekrutteringsbistand-container
          cluster: dev-gcp
        - application: rekrutteringsbistand
          cluster: dev-gcp
        - application: rekrutteringsbistand-frontend
          cluster: dev-gcp
        - application: rekrutteringsbistand-kandidat-api
          cluster: dev-fss
        - application: rekrutteringsbistand-kandidatvarsel-api
    outbound:
      external:
        - host: pam-ad-api.intern.dev.nav.no
        - host: rekrutteringsbistand-kandidat-api.dev-fss-pub.nais.io
        - host: arbeidsmarked-dev.openai.azure.com
          ports:
            - port: 443
  envFrom:
    - secret: openai-toi-rekrutteringsbistand-stilling
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: VIS_STILLING_AZP_NAME
      value: "dev-gcp:arbeidsgiver:vis-stilling"
    - name: KANDIDATVARSEL_AZP_NAME
      value: "dev-gcp:toi:rekrutteringsbistand-kandidatvarsel-api"
    - name: REKRUTTERINGSBISTAND_STILLING_INDEKSER_AZP_NAME
      value: "dev-gcp:toi:rekrutteringsbistand-stilling-indekser"
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: rekrutteringsbistand-stilling-rapidconsumer-1
    - name: KAFKA_RESET_POLICY
      value: "earliest"
    - name: AD_GRUPPE_JOBBSOKERRETTET
      value: "0dba8374-bf36-4d89-bbba-662447d57b94"
    - name: AD_GRUPPE_ARBEIDSGIVERRETTET
      value: "52bc2af7-38d1-468b-b68d-0f3a4de45af2"
    - name: AD_GRUPPE_UTVIKLER
      value: "a1749d9a-52e0-4116-bb9f-935c38f6c74a"
