apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-stilling-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  port: 9501
  ingresses:
    - https://rekrutteringsbistand-stilling-api.nais.preprod.local
    - https://rekrutteringsbistand-stilling-api.dev.intern.nav.no
    - https://rekrutteringsbistand-stilling-api.dev-fss-pub.nais.io
  liveness:
    path: /internal/actuator/health
    initialDelay: 30
  readiness:
    path: /internal/actuator/health
    initialDelay: 30
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  vault:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: vis-stilling
          cluster: dev-gcp
        - application: rekrutteringsbistand-stilling-indekser
          cluster: dev-gcp
          namespace: toi
        - application: rekrutteringsbistand-container
          namespace: toi
          cluster: dev-gcp
        - application: rekrutteringsbistand-kandidat-api
          namespace: toi
          cluster: dev-fss
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: VIS_STILLING_CLIENT_ID
      value: 4d3876c0-dfae-4bad-aecf-4415d549954a
    - name: REKRUTTERINGSBISTAND_STILLING_INDEKSER_CLIENT_ID
      value: 103b46ab-62ab-47e7-b51c-babdc41aaf1d
  kafka:
    pool: nav-dev
