apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-stilling-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{version}}
  port: 9501
  ingresses:
    - https://rekrutteringsbistand-stilling-api.dev.intern.nav.no
  liveness:
    path: /internal/actuator/health
    initialDelay: 30
  readiness:
    path: /internal/actuator/health
    initialDelay: 30
  replicas:
    max: 1
    min: 1
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: rekrutteringsbistand
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: vis-stilling
          cluster: dev-gcp
        - application: rekrutteringsbistand-stilling-indekser
          cluster: dev-gcp
          namespace: toi
        - application: rekrutteringsbistand-container
          namespace: toi
          cluster: dev-gcp
        - application: rekrutteringsbistand-kandidat-api
          namespace: toi
          cluster: dev-fss
    outbound:
      rules:
        - application: pam-ad-api
          cluster: dev-gcp
          namespace: teampam
        - application: rekrutteringsbistand-kandidat-api
          cluster: dev-fss
          namespace: toi
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: VIS_STILLING_CLIENT_ID
      value: 4d3876c0-dfae-4bad-aecf-4415d549954a
    - name: REKRUTTERINGSBISTAND_STILLING_INDEKSER_CLIENT_ID
      value: 103b46ab-62ab-47e7-b51c-babdc41aaf1d

