apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-stilling-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{version}}
  port: 9501
  ingresses:
    - https://rekrutteringsbistand-stilling-api.intern.nav.no
  liveness:
    path: /internal/actuator/health
    initialDelay: 30
  readiness:
    path: /internal/actuator/health
    initialDelay: 30
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: rekrutteringsbistand
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: vis-stilling
          cluster: prod-gcp
        - application: rekrutteringsbistand-stilling-indekser
          cluster: prod-gcp
          namespace: toi
        - application: rekrutteringsbistand-container
          namespace: toi
          cluster: prod-gcp
        - application: rekrutteringsbistand-kandidat-api
          namespace: toi
          cluster: prod-fss
    outbound:
      rules:
        - application: pam-ad-api
          cluster: prod-gcp
          namespace: teampam
        - application: rekrutteringsbistand-kandidat-api
          cluster: prod-fss
          namespace: toi
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: VIS_STILLING_CLIENT_ID
      value: d8e2c2ad-e073-43d1-8c1d-aa6fad6d7195
    - name: REKRUTTERINGSBISTAND_STILLING_INDEKSER_CLIENT_ID
      value: 1df98d81-f13d-46cb-a8d3-fcc3b030859e
