apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-stilling-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{version}}
  port: 9501
  ingresses:
    - https://rekrutteringsbistand-stilling-api.intern.nav.no
  liveness:
    path: /internal/actuator/health
    initialDelay: 30
  readiness:
    path: /internal/actuator/health
    initialDelay: 30
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: rekrutteringsbistand-stilling
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: vis-stilling
          namespace: arbeidsgiver
          cluster: prod-gcp
        - application: rekrutteringsbistand-stilling-indekser
          cluster: prod-gcp
          namespace: toi
        - application: rekrutteringsbistand-container
          namespace: toi
          cluster: prod-gcp
        - application: rekrutteringsbistand-kandidat-api
          namespace: toi
          cluster: prod-fss
    outbound:
      rules:
        - application: pam-ad-api
          cluster: prod-gcp
          namespace: teampam
        - application: rekrutteringsbistand-kandidat-api
          cluster: prod-fss
          namespace: toi
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: VIS_STILLING_URI
      value: "prod-gcp:arbeidsgiver:vis-stilling"
    - name: REKRUTTERINGSBISTAND_STILLING_INDEKSER_URI
      value: "prod-gcp:toi:rekrutteringsbistand-stilling-indekser"
