apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-stilling-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{version}}
  port: 9501
  ingresses:
    - https://rekrutteringsbistand-stilling-api.intern.nav.no
  liveness:
    path: /internal/actuator/health
    initialDelay: 30
  readiness:
    path: /internal/actuator/health
    initialDelay: 30
  replicas:
    max: 0
    min: 0
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: db-custom-1-3840
        diskAutoresize: true
        databases:
          - name: rekrutteringsbistand-stilling
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - NAVident
          - azp_name
        groups:
          - id: "ea34edea-1e80-4759-a1d2-fbe696cf1709"   # adGruppeModiaGenerellTilgang
          - id: "66b70a6a-3d05-47b3-8b5a-47c681dcd1d5"   # adGruppeJobbsøkerrettet
          - id: "46c8e3b2-0469-4740-983f-d8cd2b6e4fee"   # adGruppeArbeidsgiverrettet
          - id: "41080368-439f-4128-858a-afbef876431e"   # adGruppeUtvikler
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: vis-stilling
          namespace: toi
          cluster: prod-gcp
        - application: rekrutteringsbistand-stilling-indekser
          cluster: prod-gcp
        - application: rekrutteringsbistand-container
          cluster: prod-gcp
        - application: rekrutteringsbistand
          cluster: prod-gcp
        - application: rekrutteringsbistand-kandidat-api
          cluster: prod-fss
        - application: rekrutteringsbistand-kandidatvarsel-api
    outbound:
      external:
        - host: pam-ad-api.intern.nav.no
        - host: rekrutteringsbistand-kandidat-api.prod-fss-pub.nais.io
        - host: arbeidsmarked-prod.openai.azure.com
  envFrom:
    - secret: openai-toi-rekrutteringsbistand-stilling
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: VIS_STILLING_AZP_NAME
      value: "prod-gcp:toi:vis-stilling"
    - name: KANDIDATVARSEL_AZP_NAME
      value: "prod-gcp:toi:rekrutteringsbistand-kandidatvarsel-api"
    - name: REKRUTTERINGSBISTAND_STILLING_INDEKSER_AZP_NAME
      value: "prod-gcp:toi:rekrutteringsbistand-stilling-indekser"
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: rekrutteringsbistand-stilling-rapidconsumer-2
    - name: KAFKA_RESET_POLICY
      value: "earliest"
    - name: AD_GRUPPE_JOBBSOKERRETTET
      value: "66b70a6a-3d05-47b3-8b5a-47c681dcd1d5"
    - name: AD_GRUPPE_ARBEIDSGIVERRETTET
      value: "46c8e3b2-0469-4740-983f-d8cd2b6e4fee"
    - name: AD_GRUPPE_UTVIKLER
      value: "41080368-439f-4128-858a-afbef876431e"
