apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: rekrutteringsbistand-stilling-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  port: 9501
  ingresses:
    - https://rekrutteringsbistand-stilling-api.nais.adeo.no
    - https://rekrutteringsbistand-stilling-api.intern.nav.no
    - https://rekrutteringsbistand-stilling-api.prod-fss-pub.nais.io
  liveness:
    path: /internal/actuator/health
    initialDelay: 30
  readiness:
    path: /internal/actuator/health
    initialDelay: 30
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  vault:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: vis-stilling
          cluster: prod-gcp
        - application: rekrutteringsbistand-stilling-indekser
          cluster: prod-gcp
        - application: rekrutteringsbistand-stillingssok
          namespace: toi
          cluster: prod-gcp
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: VIS_STILLING_CLIENT_ID
      value: d8e2c2ad-e073-43d1-8c1d-aa6fad6d7195
    - name: REKRUTTERINGSBISTAND_STILLING_INDEKSER_CLIENT_ID
      value: 1b0ecc97-08f6-423c-87ff-774167cd7c28
  kafka:
    pool: nav-prod
